apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - name: tcp-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: ${FIP}

