apiVersion: v1
kind: Pod
metadata:
  name: busybox-alpine-64m
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo The busybox is running! && sleep 3600']
    resources:
      limits:
        memory: 32Mi
  - name: alpine
    image: alpine
    command: ['sh', '-c', 'echo The alpine is running! && sleep 3600']
    resources:
      limits:
        memory: 32Mi
