apiVersion: v1
kind: Pod
metadata:
  name: nginx-mongo-17g
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: 8Gi
  - name: mongo
    image: mongo
    resources:
      limits:
        memory: 9Gi
